/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CustomerRouteImport } from './routes/_customer'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CustomerIndexRouteImport } from './routes/_customer/index'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as CustomerPlaceOrderRouteImport } from './routes/_customer/place-order'
import { Route as CustomerOrdersRouteImport } from './routes/_customer/orders'
import { Route as CustomerCartRouteImport } from './routes/_customer/cart'
import { Route as CustomerAccountRouteImport } from './routes/_customer/account'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AdminProductAddRouteImport } from './routes/admin/product_/add'
import { Route as AdminProductProductIdRouteImport } from './routes/admin/product_/$productId'
import { Route as CustomerProductProductIdRouteImport } from './routes/_customer/product_.$productId'
import { Route as AdminProductEditProductIdRouteImport } from './routes/admin/product_/edit.$productId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/_customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerPlaceOrderRoute = CustomerPlaceOrderRouteImport.update({
  id: '/place-order',
  path: '/place-order',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerOrdersRoute = CustomerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCartRoute = CustomerCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerAccountRoute = CustomerAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => CustomerRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AdminProductAddRoute = AdminProductAddRouteImport.update({
  id: '/product_/add',
  path: '/product/add',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductProductIdRoute = AdminProductProductIdRouteImport.update({
  id: '/product_/$productId',
  path: '/product/$productId',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerProductProductIdRoute =
  CustomerProductProductIdRouteImport.update({
    id: '/product_/$productId',
    path: '/product/$productId',
    getParentRoute: () => CustomerRoute,
  } as any)
const AdminProductEditProductIdRoute =
  AdminProductEditProductIdRouteImport.update({
    id: '/product_/edit/$productId',
    path: '/product/edit/$productId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof CustomerIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/account': typeof CustomerAccountRoute
  '/cart': typeof CustomerCartRoute
  '/orders': typeof CustomerOrdersRoute
  '/place-order': typeof CustomerPlaceOrderRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/product/$productId': typeof CustomerProductProductIdRoute
  '/admin/product/$productId': typeof AdminProductProductIdRoute
  '/admin/product/add': typeof AdminProductAddRoute
  '/admin/product/edit/$productId': typeof AdminProductEditProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof CustomerIndexRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/account': typeof CustomerAccountRoute
  '/cart': typeof CustomerCartRoute
  '/orders': typeof CustomerOrdersRoute
  '/place-order': typeof CustomerPlaceOrderRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin': typeof AdminIndexRoute
  '/product/$productId': typeof CustomerProductProductIdRoute
  '/admin/product/$productId': typeof AdminProductProductIdRoute
  '/admin/product/add': typeof AdminProductAddRoute
  '/admin/product/edit/$productId': typeof AdminProductEditProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_customer': typeof CustomerRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_customer/account': typeof CustomerAccountRoute
  '/_customer/cart': typeof CustomerCartRoute
  '/_customer/orders': typeof CustomerOrdersRoute
  '/_customer/place-order': typeof CustomerPlaceOrderRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/_customer/': typeof CustomerIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_customer/product_/$productId': typeof CustomerProductProductIdRoute
  '/admin/product_/$productId': typeof AdminProductProductIdRoute
  '/admin/product_/add': typeof AdminProductAddRoute
  '/admin/product_/edit/$productId': typeof AdminProductEditProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/signin'
    | '/signup'
    | '/account'
    | '/cart'
    | '/orders'
    | '/place-order'
    | '/admin/orders'
    | '/admin/'
    | '/product/$productId'
    | '/admin/product/$productId'
    | '/admin/product/add'
    | '/admin/product/edit/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/account'
    | '/cart'
    | '/orders'
    | '/place-order'
    | '/admin/orders'
    | '/admin'
    | '/product/$productId'
    | '/admin/product/$productId'
    | '/admin/product/add'
    | '/admin/product/edit/$productId'
  id:
    | '__root__'
    | '/_auth'
    | '/_customer'
    | '/admin'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_customer/account'
    | '/_customer/cart'
    | '/_customer/orders'
    | '/_customer/place-order'
    | '/admin/orders'
    | '/_customer/'
    | '/admin/'
    | '/_customer/product_/$productId'
    | '/admin/product_/$productId'
    | '/admin/product_/add'
    | '/admin/product_/edit/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_customer': {
      id: '/_customer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_customer/': {
      id: '/_customer/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_customer/place-order': {
      id: '/_customer/place-order'
      path: '/place-order'
      fullPath: '/place-order'
      preLoaderRoute: typeof CustomerPlaceOrderRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/orders': {
      id: '/_customer/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof CustomerOrdersRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/cart': {
      id: '/_customer/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CustomerCartRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/account': {
      id: '/_customer/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof CustomerAccountRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/product_/add': {
      id: '/admin/product_/add'
      path: '/product/add'
      fullPath: '/admin/product/add'
      preLoaderRoute: typeof AdminProductAddRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/product_/$productId': {
      id: '/admin/product_/$productId'
      path: '/product/$productId'
      fullPath: '/admin/product/$productId'
      preLoaderRoute: typeof AdminProductProductIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_customer/product_/$productId': {
      id: '/_customer/product_/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof CustomerProductProductIdRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/product_/edit/$productId': {
      id: '/admin/product_/edit/$productId'
      path: '/product/edit/$productId'
      fullPath: '/admin/product/edit/$productId'
      preLoaderRoute: typeof AdminProductEditProductIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CustomerRouteChildren {
  CustomerAccountRoute: typeof CustomerAccountRoute
  CustomerCartRoute: typeof CustomerCartRoute
  CustomerOrdersRoute: typeof CustomerOrdersRoute
  CustomerPlaceOrderRoute: typeof CustomerPlaceOrderRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerProductProductIdRoute: typeof CustomerProductProductIdRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerAccountRoute: CustomerAccountRoute,
  CustomerCartRoute: CustomerCartRoute,
  CustomerOrdersRoute: CustomerOrdersRoute,
  CustomerPlaceOrderRoute: CustomerPlaceOrderRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerProductProductIdRoute: CustomerProductProductIdRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface AdminRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductProductIdRoute: typeof AdminProductProductIdRoute
  AdminProductAddRoute: typeof AdminProductAddRoute
  AdminProductEditProductIdRoute: typeof AdminProductEditProductIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrdersRoute: AdminOrdersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductProductIdRoute: AdminProductProductIdRoute,
  AdminProductAddRoute: AdminProductAddRoute,
  AdminProductEditProductIdRoute: AdminProductEditProductIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
